Repository Automattic/jetpack-beta, pull requests merged in 2019-07, with the labels that each got.

#90 Tracking: add tracking on the toggles, bug report submissions, and branch activation buttons
  admin/admin.js
  admin/main.php
  jetpack-beta-admin.php
Labels: [Pri] Normal, [Status] Needs Review, [Type] Enhancement

#92 Download tags directly from wp.org SVN
  admin/admin.js
  admin/main.php
  jetpack-beta-admin.php
  jetpack-beta.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#89 Add plugin options to sync whitelist
  jetpack-beta.php
Labels: [Status] Ready to Merge, [Type] Janitorial

#91 Added a custom error handler that saves to Jetpack log.
  jetpack-beta.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#88 Add/to-test section in autoupdate email
  jetpack-beta.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#94 Update plugin version to ship latest round of changes
  jetpack-beta.php
Labels: [Pri] Normal, [Status] Ready to Merge, [Type] Janitorial
